export const InitialCards = [
    {
        value: "1",
        type: "story point",
        shortType: "SP",
        selected: false,
        closed: false,
        editable: true,
      },
      {
        value: "2",
        type: "story point",
        shortType: "SP",
        selected: false,
        closed: false,
        editable: true,
      },
      {
        value: "3",
        type: "story point",
        shortType: "SP",
        selected: false,
        closed: false,
        editable: true,
      },
      {
        value: "5",
        type: "story point",
        shortType: "SP",
        selected: false,
        closed: false,
        editable: true,
      },
      {
        value: "unknown",
        type: "cup",
        shortType: "SP",
        selected: false,
        closed: false,
        editable: true,
      },
    ]